# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rembrandt/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rembrandt)

$(call add-radio-file-sha1-checked,radio/apusys.img,d151474af2cf5c00b2c96ddab3f21837963e07c5)
$(call add-radio-file-sha1-checked,radio/audio_dsp.img,6057175a4395469d41e5c64aa6dd061248780f34)
$(call add-radio-file-sha1-checked,radio/ccu.img,89c7f947d34bc1f1ab800f63a2b81627cff71b41)
$(call add-radio-file-sha1-checked,radio/dpm.img,78417aaa0cbb39cfd05fe794fb710003f69ce8ab)
$(call add-radio-file-sha1-checked,radio/dtbo.img,61e4a1462cc8642447149efa362db774668801ad)
$(call add-radio-file-sha1-checked,radio/gpueb.img,74d30078aa2465e29a514db96127c66221a36c97)
$(call add-radio-file-sha1-checked,radio/gz.img,9b404a9bff4fa5c60a6faa2f6a5f20156c98111b)
$(call add-radio-file-sha1-checked,radio/lk.img,49986f76030ab71408d5f9d91212f734b687de2e)
$(call add-radio-file-sha1-checked,radio/logo.img,7aa3f507d7310ebb64c668ff38832d985738d87b)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,679c03c2c3c08162094a8fc7d76cde16df651664)
$(call add-radio-file-sha1-checked,radio/mcupm.img,68b702ecdf72c42dae03672a7fc7d748a515aae1)
$(call add-radio-file-sha1-checked,radio/md1img.img,22b320aa904115af16add7b28a059fa2442798e8)
$(call add-radio-file-sha1-checked,radio/mvpu_algo.img,cb0f9f712a249b1298d9db1a8fbc98b968d0bb0f)
$(call add-radio-file-sha1-checked,radio/pi_img.img,f95a63b712386409afdb47099b593db63879f66d)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,8a328a075046c8e2080f63e7cc7ecf0d5bcd1d2f)
$(call add-radio-file-sha1-checked,radio/scp.img,6d2fb1cc28d8a64f1b70dc0549ec921acdd1d9a9)
$(call add-radio-file-sha1-checked,radio/spmfw.img,8088832a0a4a4fb46b9a77367ad4d9eac2c789be)
$(call add-radio-file-sha1-checked,radio/sspm.img,530d5a591b24096068b8e80482bd8edfbcf458ef)
$(call add-radio-file-sha1-checked,radio/tee.img,5d30a195c4c27352a23ec2bb4880e68ffceb733d)
$(call add-radio-file-sha1-checked,radio/vcp.img,a4dee3f43cca581d2a01d064d02202800e9a249c)

endif
