# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rembrandt/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    apusys \
    audio_dsp \
    ccu \
    dpm \
    dtbo \
    gpueb \
    gz \
    lk \
    logo \
    mcf_ota \
    mcupm \
    md1img \
    mvpu_algo \
    pi_img \
    preloader_raw \
    scp \
    spmfw \
    sspm \
    tee \
    vcp
